name: asean2024-pyrad-course
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy<1.25
  - bottleneck
  - scipy
  - matplotlib
  - cartopy
  - pandas
  - xarray
  - pydda
  - pyart_mch==1.8.6
  - xradar
  - pygrib
  - wradlib
  - sphinx=5.0
  - dask
  - tqdm
  - hvplot
  - rioxarray
  - geopandas
  - datashader
  - pyrad_mch=1.8.8
  - gdal=3.5.2
  - cookiecutter
  # this is needed for notebooks
  - pip
  - jupyter-book
  - pyviz_comms>=2.0
  - nbstripout
  - metpy
  - zip
  - certifi>=2023.07.22
  - cryptography>=41.0.3
  - semver>=3.0.1
  - nbgitpuller
  - pip
  - pip:
      - tornado>=6.3.3
      - sphinx-pythia-theme
      - cmweather